### ISSUE TITLE
Can not compile for ESP8266

### ISSUE THREAD

**Issue by ryuenma** [saghonfly/SimpleEspNowConnection#14]
Hi, thank you for making this library.

I used this for my project, which has the criteria of being able to switch from using ESP32 to ESP8266 vice versa for the Master-Slave configs. for now i have finished making the one for ESP32 and it works fine, it is able to compile and flashed normally.

but when i switched to NodeMCU 1.0 (the board i'm using for ESP8266), the Arduino IDE says it can't compile.

![image](https://user-images.githubusercontent.com/71396519/174524162-4291fdd2-6625-4f02-867a-0d425c53ff4a.png)

![image](https://user-images.githubusercontent.com/71396519/174524016-fc2b9e3c-78fe-4837-b0bd-000c1874ae19.png)

at first, i was surprised and thought it was my code that was wrong, but after i tried compiling your example sketch, none of them would compile and give the same error as the above screenshot.

is there any workaround/bypass for this? thank you

EDIT:

i tried compilingy your sketch on another pc, and it works. the difference is that my main pc that i got the error message was running a Ryzen 3 on Windows 10, while the one that works is using an Intel Core i7 on Windows 11. Is this really the cause of the error (?)

![image](https://user-images.githubusercontent.com/71396519/174525522-74e19c67-e51c-4691-9a2d-9e6265ca3c52.png)

the exact same sketch example, but this time there is no errors at all

**Comment by awardblvr** [comment]
I was able to fix this by changing ... (Here's the patch if anyone wants to apply it:)

```
From d4b8d09ed57debd86aa4c897952d1af0c1f6e43b Mon Sep 17 00:00:00 2001
From: Andrew Ward <awardservices@gmail.com>
Date: Fri, 16 Sep 2022 16:15:35 -0700
Subject: [PATCH] Fix return type declaration for one of the two deleteBuffer()
 prototypes

---
 src/SimpleEspNowConnection.cpp | 2 +-
 src/SimpleEspNowConnection.h   | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/src/SimpleEspNowConnection.cpp b/src/SimpleEspNowConnection.cpp
index a98ce67..15a00ac 100644
--- a/src/SimpleEspNowConnection.cpp
+++ b/src/SimpleEspNowConnection.cpp
@@ -182,7 +182,7 @@ uint8_t* SimpleEspNowConnection::DeviceMessageBuffer::getBuffer(const uint8_t *d
 	return bu;
 }
 
-bool SimpleEspNowConnection::DeviceMessageBuffer::deleteBuffer(const uint8_t *device, long id)
+void SimpleEspNowConnection::DeviceMessageBuffer::deleteBuffer(const uint8_t *device, long id)
 {
     for(int i = 0;i<MaxBufferSize; i++)
     {
diff --git a/src/SimpleEspNowConnection.h b/src/SimpleEspNowConnection.h
index 2fc7f17..52a48cb 100644
--- a/src/SimpleEspNowConnection.h
+++ b/src/SimpleEspNowConnection.h
@@ -116,7 +116,7 @@ class SimpleEspNowConnection
 			SimpleEspNowConnection::DeviceMessageBuffer::DeviceBufferObject* getNextBuffer();
 			bool isSendBufferEmpty();
 			bool deleteBuffer(SimpleEspNowConnection::DeviceMessageBuffer::DeviceBufferObject* dbo);
-			bool deleteBuffer(const uint8_t *device, long id);
+			void deleteBuffer(const uint8_t *device, long id);
 
 			DeviceBufferObject *_dbo[MaxBufferSize]; // buffer for messages			
 	};
-- 
2.37.1


```

**Comment by ryuenma** [comment]
> I was able to fix this by changing ... (Here's the patch if anyone wants to apply it:)
> 
> ```
> From d4b8d09ed57debd86aa4c897952d1af0c1f6e43b Mon Sep 17 00:00:00 2001
> From: Andrew Ward <awardservices@gmail.com>
> Date: Fri, 16 Sep 2022 16:15:35 -0700
> Subject: [PATCH] Fix return type declaration for one of the two deleteBuffer()
>  prototypes
> 
> ---
>  src/SimpleEspNowConnection.cpp | 2 +-
>  src/SimpleEspNowConnection.h   | 2 +-
>  2 files changed, 2 insertions(+), 2 deletions(-)
> 
> diff --git a/src/SimpleEspNowConnection.cpp b/src/SimpleEspNowConnection.cpp
> index a98ce67..15a00ac 100644
> --- a/src/SimpleEspNowConnection.cpp
> +++ b/src/SimpleEspNowConnection.cpp
> @@ -182,7 +182,7 @@ uint8_t* SimpleEspNowConnection::DeviceMessageBuffer::getBuffer(const uint8_t *d
>  	return bu;
>  }
>  
> -bool SimpleEspNowConnection::DeviceMessageBuffer::deleteBuffer(const uint8_t *device, long id)
> +void SimpleEspNowConnection::DeviceMessageBuffer::deleteBuffer(const uint8_t *device, long id)
>  {
>      for(int i = 0;i<MaxBufferSize; i++)
>      {
> diff --git a/src/SimpleEspNowConnection.h b/src/SimpleEspNowConnection.h
> index 2fc7f17..52a48cb 100644
> --- a/src/SimpleEspNowConnection.h
> +++ b/src/SimpleEspNowConnection.h
> @@ -116,7 +116,7 @@ class SimpleEspNowConnection
>  			SimpleEspNowConnection::DeviceMessageBuffer::DeviceBufferObject* getNextBuffer();
>  			bool isSendBufferEmpty();
>  			bool deleteBuffer(SimpleEspNowConnection::DeviceMessageBuffer::DeviceBufferObject* dbo);
> -			bool deleteBuffer(const uint8_t *device, long id);
> +			void deleteBuffer(const uint8_t *device, long id);
>  
>  			DeviceBufferObject *_dbo[MaxBufferSize]; // buffer for messages			
>  	};
> -- 
> 2.37.1
> ```

is there any chance that you can explain how to use the patch? as i am still new at this and i can't seem to find the exact codes 😅

**Comment by awardblvr** [comment]
Sorry... no.


This is a learning opty for you.. I heartily encourage to keep on your
learning path.. Possibly google "How does a git patch work?"
