### ISSUE TITLE
Connection Status in the loop

### ISSUE THREAD

**Issue by Whopper500** [saghonfly/SimpleEspNowConnection#4]
Hello!
First of all: Many Thanks for your contribution!

Your Client example includes an ongoing Serial connection. I was wondering if it is possible to use the ESP8266 and your libary as a Sensor-Client in battery mode. Therefore it qould be very useful to add somekind of "Connection Status" in the loop. Example:

void loop {
<OTA things ....>

   if (SimpleEspNowConnection_status == false) {
      simpleEspConnection.startPairing(30);
   } else
      simpleEspConnection.sendMessage(putsensordatahere);
   }
}

Could you please give some information if this is possible?

See below for another example (ESP32 library).

Thanks a lot an Regards from Germany
Martin

void loop() {
  if (millis() - lasttime_scan > 5000) {
    // In the loop we scan for slave
    
    lasttime_scan = millis();
  }
  
  
  // If Slave is found, it would be populate in `slave` variable
  // We will check if `slave` is defined and then we proceed further
  if (slave.channel == CHANNEL) { // check if slave channel is defined
    // `slave` is defined
    // Add slave as peer if it has not been added already
    bool isPaired = manageSlave();
    if (isPaired) {
      // pair success or already paired
      // Send data to device
      sendData();
    } else {
      delay(1000);
      ScanForSlave();
      // slave pair failed
      Serial.println("Slave pair failed!");
    }
  }
  else {
    delay(1000);
    ScanForSlave();
    // No slave found to process
  }

}

**Comment by saghonfly** [comment]
Hello Whopper500,

thanks a lot for trying out this library!

I'm not sure if I got your request right.
From the idea of the library, the client and server (master, slave) are loosely coupled.
Means, when you set both in pairing mode, both are getting the address of the partner and you can use it in your sketch to send a message from server to the known clients or from the client to the known server.
Definitive missing is the acknowledge whether the partner has gotten the message. (will be added soon)
Also what I could be helpful, is a periodic 'ping' which checks if the server is still alive.
A ping from server to the the clients could also be possible, but in most use cases (I assume..) for a client is to run in sleep mode most of the time so that server will not reach the client in this mode.

What do you think, would this an idea?

Gruss
Erich

**Comment by Whopper500** [comment]
Hi Erich,

somekind of Ping is exactly what I am asking for. Because: ESPnow is
perfect for unidirectional communication e.g. from several Senders to one
Receiver. If the Receiver is offline, Clients can turn off completely or go
to DeepSleep.



One approach could be the use of the receive-callback. E.g. any 100th
message the receive callback turns on and the Client analyzes if the
message was received. If not, go to sleep.



Grüße zurück!



*Von:* Erich O. Pintar <notifications@github.com>
*Gesendet:* Montag, 11. Mai 2020 06:30
*An:* saghonfly/SimpleEspNowConnection <
SimpleEspNowConnection@noreply.github.com>
*Cc:* Whopper500 <martin.rixen@gmail.com>; Author <author@noreply.github.com
>
*Betreff:* Re: [saghonfly/SimpleEspNowConnection] Connection Status in the
loop (#4)



Hello Whopper500,

thanks a lot for trying out this library!

I'm not sure if I got your request right.
From the idea of the library, the client and server (master, slave) are
loosely coupled.
Means, when you set both in pairing mode, both are getting the address of
the partner and you can use it in your sketch to send a message from server
to the known clients or from the client to the known server.
Definitive missing is the acknowledge whether the partner has gotten the
message. (will be added soon)
Also what I could be helpful, is a periodic 'ping' which checks if the
server is still alive.
A ping from server to the the clients could also be possible, but in most
use cases (I assume..) for a client is to run in sleep mode most of the
time so that server will not reach the client in this mode.

What do you think, would this an idea?

Gruss
Erich

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/saghonfly/SimpleEspNowConnection/issues/4#issuecomment-626462940>,
or unsubscribe

**Comment by saghonfly** [comment]
Dear Martin,

 may I ask you to try out the current version from the dev branch?
I also added two more samples for a sensor server[gateway] and a simple sensor with a pairing button and a button which should notify if pressed or not.
On server side I added a very simple concept how an update of such a sensor could be possible, even if it goes down to sleep very fast after publishing the sensor result.

Would be nice if you could check whether this will fit to your request.

Gruss
Erich

**Comment by saghonfly** [comment]
Hi Martin,
 
 if you take a look on the current released version (1.0.4) you will find a 'canSend()' method which can be used in the loop to check whether sending of a message is possible at this point of time.
Also the samples are updated so you can see how it should work.

Gruss
Erich
